name: python-calc
version: 1.0.0
summary: Makes a calculation in Python
#title: SDK Python Calculation Sample
description: 'Sample App in Python using Data Layer subscriptions
'
base: core18
confinement: strict
grade: stable

apps:

  client:
    command: main.py
    plugs:
      - network
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

parts:

  client:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - ../../whl/ctrlx_datalayer-1.4.0-py3-none-any.whl
      - ../../whl/ctrlx_fbs-1.0.0-py3-none-any.whl
      - flatbuffers~=1.12

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
